name: Deploy MultiDocker
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t rbalajee/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true rbalajee/react-test npm test

            - run: docker build -t rbalajee/multi-client ./client
            - run: docker build -t rbalajee/multi-nginx ./nginx
            - run: docker build -t rbalajee/multi-server ./server
            - run: docker build -t rbalajee/multi-worker ./worker

            - run: docker push rbalajee/multi-client
            - run: docker push rbalajee/multi-nginx
            - run: docker push rbalajee/multi-server
            - run: docker push rbalajee/multi-worker
